apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: docs
          image: ghcr.io/${git_username}/${git_repo_name}/docs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
