apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Official Envoy Gateway install manifest
  - https://github.com/envoyproxy/gateway/releases/download/v1.3.0/install.yaml
  # Custom EnvoyProxy and GatewayClass config
  - config.yaml
