apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Official Envoy Gateway install manifest
  # Custom EnvoyProxy and GatewayClass cresources:
  - https://github.com/envoyproxy/gateway/releases/download/v1.3.0/install.yaml
  - config.yaml
  - static-dns.yaml
