apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Official Envoy Gateway install manifest
  # Custom EnvoyProxy and GatewayClass config
  - config.yaml
  - static-dns.yaml
